matrix:
    - name: YAML
      aspell:
        lang: en
        ignore-case: true
      dictionary:
        encoding: utf-8
        wordlists:
          - .github/wordlist.txt
      sources:
      - '*.yml'
      default_encoding: utf-8
