on:
  pull_request_target:
    types:
      - opened

name: PR Labeler Workflow

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
      labels: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
