name: "Promote Experimental Rules To Test"

on:
  push:
    branches:
        - "*"
  schedule:
    - cron: "30 1 1,15 * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pull-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: true
        ref: rules-promotions
    - name: Pull Master Branch
      run: |
        git fetch
        git rebase origin master
  promote:
    runs-on: ubuntu-latest
    needs: pull-master
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11
      - name: Execute Rule Promoter Script
        run: |
          pip install PyYAML
          python tests/promote_rules_status.py
      - name: Create Pull Request
        run: |
          gh pr create -B master --title 'Promote Older Rules From `experimental` to `test`' --body 
            '
            ### Summary of the Pull Request

            This PR promotes and upgrade the status of rules that haven't been changed for over 300 days from `experimental` to `test`

            ### Changelog

            chore: promote older rules status from `experimental` to `test`
            '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

