name: Sigma Rule Automation

on:
  workflow_dispatch:
    inputs:
      cve_id:
        description: 'Enter CVE ID'
        required: true
        default: 'CVE-2025-49144'

jobs:
  generate-sigma-rule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better branch management

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyyaml requests openai

      - name: Configure Git
        run: |
          git config --global user.name "SigmaBot"
          git config --global user.email "sigma-bot@github.com"
          # Configure git to handle large files and improve performance
          git config --global core.compression 9
          git config --global http.postBuffer 524288000

      - name: Run SigmaAgent
        run: |
          python secrets/SigmaAgent.py --cve ${{ github.event.inputs.cve_id }} --auto-submit --config secrets/sigma_config.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Cleanup old branches (optional)
        if: always()
        run: |
          # List all branches for debugging
          echo "Current branches:"
          git branch -a
          
          # Note: Branch cleanup should be done manually or through a separate workflow
          # to avoid conflicts with active PRs
