name: Sigma Rule Automation

on:
  workflow_dispatch:
    inputs:
      cve_id:
        description: 'Enter CVE ID'
        required: true
        default: 'CVE-2025-49144'

jobs:
  generate-sigma-rule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyyaml requests openai

      - name: Configure Git
        run: |
          git config --global user.name "SigmaBot"
          git config --global user.email "sigma-bot@github.com"

      - name: Run SigmaAgent
        run: |
          python secrets/SigmaAgent.py --cve ${{ github.event.inputs.cve_id }} --auto-submit --config secrets/sigma_config.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{secrets.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}}
